# Generated by Django 5.2.8 on 2025-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_age", models.IntegerField()),
                (
                    "person_gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "person_education",
                    models.CharField(
                        choices=[
                            ("High School", "High School"),
                            ("Associate", "Associate"),
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("Doctorate", "Doctorate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("person_income", models.FloatField()),
                ("person_emp_exp", models.FloatField()),
                (
                    "person_home_ownership",
                    models.CharField(
                        choices=[
                            ("Rent", "Rent"),
                            ("Own", "Own"),
                            ("Mortgage", "Mortgage"),
                        ],
                        max_length=10,
                    ),
                ),
                ("loan_amnt", models.FloatField()),
                (
                    "loan_intent",
                    models.CharField(
                        choices=[
                            ("Personal", "Personal"),
                            ("Home", "Home"),
                            ("Education", "Education"),
                            ("Medical", "Medical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("loan_int_rate", models.FloatField()),
                ("loan_percent_income", models.FloatField()),
                ("cb_person_cred_hist_length", models.FloatField()),
                ("credit_score", models.FloatField()),
                (
                    "previous_loan_defaults_on_file",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                ("prediction", models.CharField(blank=True, max_length=20, null=True)),
                ("prediction_probability", models.FloatField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
