# Generated by Django 5.2.8 on 2025-11-20 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile", models.AutoField(primary_key=True, serialize=False)),
                ("middle_name", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=50, null=True, unique=True)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, max_length=20, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, null=True, unique=True),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("Ghana", "Ghana"),
                            ("UK", "UK"),
                            ("USA", "USA"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Adamawa", "Adamawa"),
                            ("Akwa Ibom", "Akwa Ibom"),
                            ("Anambra", "Anambra"),
                            ("Bauchi", "Bauchi"),
                            ("Bayelsa", "Bayelsa"),
                            ("Benue", "Benue"),
                            ("Borno", "Borno"),
                            ("Cross River", "Cross River"),
                            ("Delta", "Delta"),
                            ("Ebonyi", "Ebonyi"),
                            ("Edo", "Edo"),
                            ("Ekiti", "Ekiti"),
                            ("Enugu", "Enugu"),
                            ("Gombe", "Gombe"),
                            ("Imo", "Imo"),
                            ("Jigawa", "Jigawa"),
                            ("Kaduna", "Kaduna"),
                            ("Kano", "Kano"),
                            ("Katsina", "Katsina"),
                            ("Kebbi", "Kebbi"),
                            ("Kogi", "Kogi"),
                            ("Kwara", "Kwara"),
                            ("Lagos", "Lagos"),
                            ("Nasarawa", "Nasarawa"),
                            ("Niger", "Niger"),
                            ("Ogun", "Ogun"),
                            ("Ondo", "Ondo"),
                            ("Osun", "Osun"),
                            ("Oyo", "Oyo"),
                            ("Plateau", "Plateau"),
                            ("Rivers", "Rivers"),
                            ("Sokoto", "Sokoto"),
                            ("Taraba", "Taraba"),
                            ("Yobe", "Yobe"),
                            ("Zamfara", "Zamfara"),
                            ("FCT Abuja", "FCT Abuja"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("city", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("occupation", models.CharField(max_length=50, null=True)),
                (
                    "means_of_identity",
                    models.ImageField(null=True, upload_to="identityImage/"),
                ),
                ("BVN", models.CharField(max_length=11, null=True, unique=True)),
                ("NIN", models.CharField(max_length=11, null=True, unique=True)),
                (
                    "electricity_bills",
                    models.FileField(null=True, upload_to="particularsImage/"),
                ),
                (
                    "profile_passport",
                    models.ImageField(null=True, upload_to="userimage/"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("CEO", "CEO"),
                            ("GMD", "GMD"),
                            ("CTO", "CTO"),
                            ("Supervisor", "Supervisor"),
                            ("Accountant", "Accountant"),
                            ("Marketer", "Marketer"),
                            ("Cashier", "Cashier"),
                            ("Driver", "Driver"),
                            ("Customer care", "Customer care"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Engaged", "Engaged"),
                            ("Married", "Married"),
                            ("Divorce", "Divorce"),
                            ("Complicated", "Complicated"),
                            ("Widow", "Widow"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("staff", models.BooleanField(default=False, null=True)),
                (
                    "user_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Retired", "Retired"),
                            ("Suspended", "Suspended"),
                            ("Freeze", "Freeze"),
                            ("On Leave", "On Leave"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
